### ISSUE TITLE
Be more restrictive with version string?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#101]
Currently, `version` can be any string:

```python
backend = audbackend.create(
    'file-system',
    'host',
    'repo',
)

src_file = 'src.pth'
src_path = audeer.touch(src_file)

backend.put_file(src_file, 'file.txt', 'could-be-any-thing')
backend.ls()
```
```
[('file.txt', 'could-be-any-thing')]
```

Do we call it a feature or should we be more restrictive? E.g. raise an error if `version` is not conform with `audeer.is_semantic_version()`?

**Comment by hagenw** [comment]
Good question, with `audmodel` people used already customs strings as versions, so I guess we would no longer compatible with it.

**Comment by frankenjoe** [comment]
Ok, so let's call it a feature :) And maybe it's indeed best to not restrict it and let the application decided what is a valid version. However, we should at least have a check that the version string does not contain invalid characters or `/`.

**Comment by frankenjoe** [comment]
Done in #120
