### ISSUE TITLE
Raise error if local folder does not exist?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#107]
With `audbackend.get_file()` we currently expect the path to a local file and if the folder does not exist we create it. The latter behavior is currently not documented, but since it is not a default behavior (usually a function fails if the directory does not exist) we should do so.

However, we could also think about changing the behavior and raise an error if the folder does not exist. If we decide to do that we could also support downloading a file to a folder and in that case automatically expand with the filename of the backend path.

**Comment by hagenw** [comment]
Usually, I'm in favor of creating the folder automatically, but you are right then we cannot so easy support the second case, which might be what most other APIs do.

**Comment by frankenjoe** [comment]
Maybe we can actually support both:

1. if `path` is an existing file we overwrite it
2. if `path` is an existing folder we download the file it using the name of the file on the backend
3. if `path` does not exist and does not end on the file separator of the system we create `os.path.dirname(path)`
4. if `path` does not exist and does end on a file separator we create `os.path(path)` and download the file using the name of the file on the backend

**Comment by hagenw** [comment]
That's true, it would work, but it will result in quite different results depending on the current existing folders.
For example
```python
backend.get_file('file.txt', 'folder', '1.0.0')
```
will create the file `folder/file.txt` if `folder` is an existing folder.
If not, it will create the file `folder`.

**Comment by hagenw** [comment]
What will happen when calling
```python
backend.get_file('file.txt', 'folder', '1.0.0')
```
?

When `folder` exists we will end up with `folder/file.txt`.
When `folder` does not exist, will it store the file under `./folder` or under `./file.txt`?

**Comment by frankenjoe** [comment]
> When folder does not exist, will it store the file under ./folder or under ./file.txt?

```
backend.get_file('file.txt', 'folder', '1.0.0')
```

under `./folder`

```
backend.get_file('file.txt', 'folder/', '1.0.0')
```

under `./folder/file.txt`

**Comment by frankenjoe** [comment]
If we think that is too confusion we should probably stay with the current solution that always expects that `path` is not a directory and possibly creates `os.dirname(path)`. Of course this would still mean that `backend.get_file('file.txt', 'folder', '1.0.0')` will be stored as `./folder`.

**Comment by hagenw** [comment]
Yes, I think this would be less confusing.

**Comment by frankenjoe** [comment]
Ok, then we simply stay with the current implementation.
