### ISSUE TITLE
DOC: update authentication section

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#114]
In the authentication section we still link to `audfactory`, but since we don't rely on the package any longer we should probably directly include this information in the documentation `audbackend`.

![image](https://user-images.githubusercontent.com/10383417/235625586-93bb318d-a5a1-4368-b78c-20578866f65a.png)

**Comment by frankenjoe** [comment]
Actually, we might simply want to remove it since it authentication is now documented directly in the `Artifactory` class:

![image](https://user-images.githubusercontent.com/10383417/235626736-3b4a096f-1774-47dc-be6a-17e6150051ad.png)

**Comment by hagenw** [comment]
Yes, I think it makes more sense to remove it and document it inside the documentation of the corresponding backends.
