### ISSUE TITLE
Provide script to convert repository structures

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#129]
In `audbackend` we will introduce a new structure in which files are stored on the backend (as added in https://github.com/audeering/audbackend/pull/62), changing from

```
/<folder>/<name-wo-ext>/<version>/<name-wo-ext>-<version>.<ext>
```
to
```
/<sub-path>/<version>/<name>
```

As discussed in #76 it would be useful to provide a script that can convert an existing repository structure to a new one, for example by copying the files from one repository to another one.

When dealing with Artifactory as a backend it might be more safe to first download all files, convert them, and upload them afterwards.

**Comment by frankenjoe** [comment]
With https://github.com/audeering/audbackend/pull/130 there is no longer a need to convert the repository file structure. We now offer a solution to keep working with repositories that use the old structure.

**Comment by hagenw** [comment]
I agree, there is no need for a script and we should focus on #131 instead.
