### ISSUE TITLE
Make FileSystem._checksum() faster

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#14]
As we need `audbackend.FileSystem._checksum() ` quite often, we would hugely benefit from making it as fast as possible.

Not supringsily, this was discussed for `dvc` as well: https://github.com/iterative/dvc/issues/1568

The conclusion is that [xxhash](https://github.com/Cyan4973/xxHash) is the fastest solution.
It is also available for Python.

```python
>>> # Using hashlib.md5()
>>> timeit.timeit("audbackend.core.utils.md5('1272-128104-0000.flac')", number=10000, setup="import audbackend")
1.984513125004014
>>> # Using xxhash.xxh128()
>>> timeit.timeit("audbackend.core.utils.md5('1272-128104-0000.flac')", number=10000, setup="import audbackend")
0.5107942969989381
```

`xxhash` is indeed faster and it has no external dependency that is nice.
But of course we have the problem that the hashes are not identical and we cannot easily switch to another has algorithm in `audb` without updating all dependency tables.

**Comment by frankenjoe** [comment]
> As we need `audbackend.FileSystem._checksum() ` quite often, we would hugely benefit from making it as fast as possible.

True, but the good thing is that we only need it during publishing.

> `xxhash` is indeed faster and it has no external dependency that is nice.

But it's not supported by `Artifactory` is it?

**Comment by hagenw** [comment]
> > `xxhash` is indeed faster and it has no external dependency that is nice.
> 
> But it's not supported by `Artifactory` is it?

That is a very good point, so we could switch only to `sha-1` or `sha-256`.

`sha-1` is slightly faster:

```python
>>> timeit.timeit("audbackend.core.utils.md5('1272-128104-0000.flac')", number=10000, setup="import audbackend")
1.5151363699987996
```

`sha-256` is of course slower:

```python
>>> timeit.timeit("audbackend.core.utils.md5('1272-128104-0000.flac')", number=10000, setup="import audbackend")
2.8006805740005802
```

So, there would be a little bit of gain switching to `sha1`, but as it breaks everything where we have used `audbackend` before, I'm not very much ion favor of it.

**Comment by hagenw** [comment]
I would suggest we not switch to another hash algorithm and close this issue or mark it as "wontfix"

**Comment by frankenjoe** [comment]
Since we need a checksum that is widely supported, it makes sense to stick with `md5`. As suggested by @hagenw I will close this issue.
