### ISSUE TITLE
Backend.ls(): pattern should match basename

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#153]
Currently we apply `pattern` to the whole path and not just the basename. This leads to the following behavior:

``` python
backend.put_file(file, '/sub/file.txt', '1.0.0')
backend.ls('/', pattern='*.txt')
```
```
[('/sub/file.txt', '1.0.0')]
```

but:

``` python
ls = backend.ls('/', pattern='f*.txt')
```
```
[]
```

This might not be the expected behavior ~~and I wonder if we should introduce a `match_basename` argument, to control what part of the file path should be matched. With such an argument the user could then do:~~

EDIT: we agreed this is a bug and the expected output should be:

``` python
ls = backend.ls('/', pattern='f*.txt')
```
```
[('/sub/file.txt', '1.0.0')]
```

**Comment by hagenw** [comment]
Reading the description of `pattern`

![image](https://github.com/audeering/audbackend/assets/173624/ffe64001-9810-49a2-97ff-e2d0ebfd5f06)

I would say the current behavior is a bug and it should anyway only match the basename.
So, I would not introduce a new argument, but change the current behavior.
