### ISSUE TITLE
Docs of backend.exists() wrongly state that error is raised if path does not exist

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#156]
In the documentation of `audbackend.Backend.exists()` it is stated

![image](https://github.com/audeering/audbackend/assets/173624/63176c5d-eee9-4c8c-8543-07c1b186e54f)

This feels strange, and it is also not the case:

```python
import audbackend

backend = audbackend.access('artifactory', 'https://audeering.jfrog.io/artifactory', 'data-public')
backend._use_legacy_file_structure()
```

```python
>>> backend.exists(backend.join('/', 'emodb', 'db.yaml'), '1.4.1')
True

>>> backend.exists(backend.join('/', 'non-existing', 'db.yaml'), '1.0.0')
False
```

**Comment by frankenjoe** [comment]
Yes, we should replace `e.g. path does not exist` with `e.g. due to a connection error`
