### ISSUE TITLE
Add public authentication() method to Artifactory backend

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#161]
In order to deprecate the [audfactory](https://github.com/audeering/audfactory) package we should add the private function `audbackend.core.artifactory._authentication()` as a public class method.

```python
username, password = audbackend.Artifactory.authentication(host)
```

This would a user allow to test which username and password would be used to authenticate with the host,
useful for debugging authentication issues, see https://audeering.github.io/audfactory/usage.html#authentication.
And it would allow to get the username, password needed for rest API requests, as in [audfactory.rest_api_get()](https://github.com/audeering/audfactory/blob/6fc6afe2e0ab53c25f7ebd946c584f5756c0466a/audfactory/core/api.py#L353-L354):
```python
    username, apikey = authentification(url)
    return requests.get(url, auth=(username, apikey))
```

**Comment by frankenjoe** [comment]
Implemented in #215
