### ISSUE TITLE
Add auth argument to provide username, password to backend

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#162]
The only way to authenticate at a backend at the moment, is to provide the credentials in a config file or an environment variable. This is fine in most cases, but not in all, e.g. when accessing the same backend with different users, one needs to set and delete environment variables.

This could be avoided by adding an `auth` variable (as in `requests.get()`) to all functions/methods that have to authenticate:
* `Backend.__init__()`
* `access()`
* `create()`
* `delete()`

The `auth` argument would then expect the tuple `(username, password)`.

**Comment by frankenjoe** [comment]
Implemented in #215
