### ISSUE TITLE
Hide backend in API documentation

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#169]
In https://github.com/audeering/audbackend/pull/167 we introduce a new abstract interface layer between backends and the user. Which means a normal user will need to look only at the interface API. For that reason we should hide parts of the backend API from the user, e.g. all the methods that are inherited from `audbackend.Backend` in `audbackend.Artifactory` and `audbackend.FileSystem` and instead add a link to the interface section.

It might still be of interest to show the API for `audbackend.Backend` as this is needed for developer who want to create a new interface.

**Comment by hagenw** [comment]
I will start working on this one.

**Comment by hagenw** [comment]
Changes to the documentation will be easier after we changed the package structure as proposed in https://github.com/audeering/audbackend/issues/170. Will pause until that has happened.

**Comment by frankenjoe** [comment]
@hagenw are you working on #170? Otherwise I can also do it.

**Comment by hagenw** [comment]
No, I'm not working on `audbackend` at the moment, feel free to start with #170.

**Comment by frankenjoe** [comment]
Now with the separation of `backend` and `interface`, I'm not completely convinced if we still have to hide parts of `audbackend.backend.*` in the API. Maybe it's sufficient if we add a note that he sub-module is only relevant for developers?

**Comment by hagenw** [comment]
I agree. I continued with #171, but I simply change the usage documentation by splitting it up into a section for users and one for developers.
