### ISSUE TITLE
Make test for single folder work under Windows

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#183]
As mentioned in https://github.com/audeering/audbackend/pull/126#discussion_r1183762375 the test for the `SingleFolder` backend is currently deactivated under Windows as it failed for unknown reasons.
This is unfortunate as it also hinders us from an easy test for the default `copy_file()` backend method under Windows, see https://github.com/audeering/audbackend/pull/181#pullrequestreview-1869594294

**Comment by frankenjoe** [comment]
Implemented in #191
