### ISSUE TITLE
Raise ValueError for path ending with "/" if file path is expected

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#206]
As mentioned in https://github.com/audeering/audbackend/pull/204#discussion_r1547793260, several backend methods do expect file path as input, and should hence raise an error if a path ends with `"/"` indicating that we are dealing with a sub-path, but not a file path.

**Comment by frankenjoe** [comment]
@hagenw I started working on this one.

**Comment by hagenw** [comment]
Solved by #208
