### ISSUE TITLE
What should backend.exists() return for non-existing backends?

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#24]
It might be that you specify a backend for which the host does not exists.

For `audbackend.FileSystem`, `backend.exists(path)` will then return `False` for every `path` variable,
but for `audbackend.Artifactory` it will fail and raise an `requests.exceptions.ConnectionError` error.

Which of those is the expected behavior when a host does not exists?

**Comment by frankenjoe** [comment]
Ideally we already raise an error when you try to create a backend with an invalid host?

**Comment by hagenw** [comment]
> Ideally we already raise an error when the user tries to create a backend with an invalid host?

Yes, I think that would be a good solution. For `FileSystem` you could even create the `host` on the fly (and maybe we even do it in some of our tests), but I would argue that it is more important that the different backends behave in the same way.

**Comment by frankenjoe** [comment]
>  but I would argue that it is more important that the different backends behave in the same way.

agree

**Comment by frankenjoe** [comment]
We now ensure that the repository must exist, see #91 otherwise an error is raised already when `audbackend.create()` is called.
