### ISSUE TITLE
Implement backend in a single folder

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#41]
This picks up a comment by @hagenw asking if every backend has to have a concept of folders: https://github.com/audeering/audbackend/issues/37#issuecomment-1114765181

Turns out, the answer is no, as the following implementation of a `SingleFolderBackend` shows (it already follows the suggestion in  #40 and implements `find()` instead of `ls()` and `glob()`).

```python
import fnmatch
import os
import shelve
import shutil
import typing

import audbackend
import audeer


class SingleFolderBackend(audbackend.Backend):

    def __init__(
            self,
            host: str,
            repository: str,
    ):
        super().__init__(audeer.safe_path(host), repository)

        self.root = audeer.mkdir(audeer.path(host, repository))
        self.map = shelve.open(audeer.safe_path(self.root, '.map'))

    def __del__(self):
        self.map.close()

    def _checksum(
            self,
            path: str,
    ) -> str:
        r"""MD5 checksum of file on backend."""
        return audbackend.core.utils.md5(path)

    def _inverse_path(
            self,
            path: str,
    ) -> (str, str, str):
        r"""Virtual file path."""
        uid = path[:8]
        folder = self.map[uid]
        version = path[9:].split('-')[-1]
        file = path[9:-len(version) - 1]
        return folder, file, version

    def _path(
            self,
            folder: str,
            name: str,
            ext: str,
            version: str,
    ) -> str:
        r"""File path on backend."""
        uid = self._uid(folder)
        self.map[uid] = folder
        file = f'{uid}-{name}{ext}-{version}'
        path = audeer.path(self.root, file)
        return path

    def _exists(
            self,
            path: str,
    ) -> bool:
        r"""Check if file exists on backend."""
        return os.path.exists(path)

    def _get_file(
            self,
            src_path: str,
            dst_path: str,
            verbose: bool,
    ):
        r"""Get file from backend."""
        shutil.copy(src_path, dst_path)

    def find(
            self,
            *,
            version: str = None,
            folder: str = None,
            pattern: str = None,
    ):
        r"""Will be implemented in BAckend."""
        folder = folder or ''
        ls = self._find(folder)
        match = set()
        for path in ls:
            f, n, v = self._inverse_path(path)
            if version is not None and v != version:
                continue
            if pattern is not None and not fnmatch.fnmatch(n, pattern):
                continue
            match.add(self.join(f, n))
        return sorted(list(match))

    def _find(
            self,
            folder: str,
    ):
        r"""List content of path."""
        ls = []
        for key, value in self.map.items():
            if value.startswith(folder):
                path = audeer.path(self.root, f'{key}*')
                match = audeer.list_file_names(path, basenames=True)
                ls.extend(match)
        return ls

    def _put_file(
            self,
            src_path: str,
            dst_path: str,
            verbose: bool,
    ):
        r"""Put file to backend."""
        shutil.copy(src_path, dst_path)

    def _remove_file(
            self,
            path: str,
    ):
        r"""Remove file from backend."""
        os.remove(path)

    def _uid(
            self,
            folder: str,
    ) -> str:
        r"""Convert folder to unique ID."""
        return audeer.uid(from_string=folder)[:8]

    def _versions(
            self,
            folder: str,
            name: str,
    ) -> typing.List[str]:
        r"""Versions of a file."""
        uid = self._uid(folder)
        pattern = f'{uid}-{name}*'
        path = audeer.path(self.root, pattern)
        vs = []
        for file in audeer.list_file_names(path):
            v = file.split('-')[-1]
            vs.append(v)
        return vs
```

Here's a test:

```
backend = SingleFolderBackend('.', 'sfb')

ret = backend.put_file('test.txt', 'sub/dir/test', '1.0.0')
print(ret)
ret = backend.put_file('test.txt', 'test.txt', '1.0.0')
print(ret)
ret = backend.put_file('test.txt', 'sub/dir/test', '1.1.0')
print(ret)
ret = backend.exists('sub/dir/test', '1.0.0')
print(ret)
ret = backend.exists('sub/dir/test', '2.0.0')
print(ret)
backend.get_file('sub/dir/test', 'check.txt', '1.0.0')
ret = backend.versions('sub/dir/test')
print(ret)
ret = backend.find()
print(ret)
ret = backend.find(folder='sub')
print(ret)
ret = backend.find(version='1.1.0')
print(ret)
ret = backend.find(pattern='*.txt')
print(ret)
```
```
.../sfb/3c6066d7-test-1.0.0
.../sfb/d41d8cd9-test.txt-1.0.0
.../sfb/3c6066d7-test-1.1.0
True
False
['1.0.0', '1.1.0']
['sub/dir/test', 'test.txt']
['sub/dir/test']
['sub/dir/test']
['test.txt']
```

**Comment by frankenjoe** [comment]
Btw: the example also shows that introducing a `folder()` function as proposed #38 does not make sense - since the backend converts a folder to an ID, there is no relation between `sub` and `sub/dir`. Both will have completely unrelated paths on the backend. But we can even pursue this further and show that `path()` does not make sense, either. E.g. if we generate a random ID for each file when we store it on the backend. In that case `path('file.txt', '1.0.0')` will return different values each time it is called. So I think we should also remove `path()` and `_path()` from `Backend` and instead always pass the virtual path to the abstract functions (currently it's anyway a mix - sometimes we pass the backend pass and sometimes the virtual path). This would also make the implementation of `SingleFolderBackend` cleaner. Cause currently we have to fill the dictionary `map` that keeps track of virtual folder to it's representation on the backend in `_path()`. But that means it is also filled with entries that are actually not on the backend, e.g. if the user calls `exists()` for a non-existing file. If we would pass the virtual path instead, we could do:

```python
    def _put_file(
            self,
            src_path: str,
            dst_path: str,   # virtual path instead of backend path
            verbose: bool,
    ):
        r"""Put file to backend."""
        dst_path_map = _path(dst_path)  # simplified
        self.map[dst_path] = dst_path_map
        shutil.copy(src_path, dst_path_map)

    def _remove_file(
            self,
            path: str,   # virtual path instead of backend path
    ):
        r"""Remove file from backend."""
        path_map = self.map[path].pop()
        os.remove(path_map)
```

This would ensure that `map` only contains paths that actually exists on the backend.

**Comment by hagenw** [comment]
I agree, and would also vote for supporting only "virtual path".
It will make it also much easier to understand the `Backend` class as a user.

**Comment by hagenw** [comment]
> This would ensure that map only contains paths that actually exists on the backend.

But would it be safe to use with multi-threading?

**Comment by hagenw** [comment]
> > This would ensure that map only contains paths that actually exists on the backend.
> 
> But would it be safe to use with multi-threading?

Another big problem will be that a user might delete files directly on the backend (e.g. Artifactory web UI).

**Comment by frankenjoe** [comment]
I guess this depends whether `shelve` is thread safe. Otherwise you are right and we have use a file lock in all places where we access `self.map`.

**Comment by frankenjoe** [comment]
> Another big problem will be that a user might delete files directly on the backend (e.g. Artifactory web UI).

Yes, but that's something a user is not supposed to do. E.g. a user can easily mess up `audb' by manually removing files. I think this is a use-case we cannot support, but instead we should assume that all interaction will be through the backend interface.

**Comment by hagenw** [comment]
> > Another big problem will be that a user might delete files directly on the backend (e.g. Artifactory web UI).
> 
> Yes, but that's something a user is not supposed to do. E.g. a user can easily mess up `audb` by manually removing files. I think this is a use-case we cannot support, but instead we should assume that all interaction will be through the backend interface.

I'm not so sure about this, as there might be use cases for which it is much simpler to fix something in the web UI than by using Python and `audbackend`.

But I also don't see a big need to track existing files in a dictionary, and would simply check if the file exists before removing.
It's also not clear to me how to fill the dictionary when instantiating the backend and you have >100,000,000 files on the backend.

**Comment by frankenjoe** [comment]
> It's also not clear to me how to fill the dictionary when instantiating the backend and you have >100,000,000 files on the backend.

I guess every file system works in more or less similar way by keeping a table with all files and where they are located on the disk. Yet, I would not recommend to use `SingleFolderBackend` with > 100,000,000 files :) I still think it's a good example to test if our `Backend` implementation makes sense.
