### ISSUE TITLE
Same virtual path can translate into different backend paths

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#49]
As the following example shows the same virtual path can translate into different backend paths depending on the `ext` argument that we pass:

```python
backend = audbackend.create(
    'artifactory',
    'https://audeering.jfrog.io/artifactory',
    'unittests-public',
)

path = 'folder/file.foo.bar'

for ext in ['', '.foo', '.foo.bar']:
    backend_path = backend._path(
        path,
        '1.0.0',
        ext,
    )
    print(backend_path)
```
```
https://audeering.jfrog.io/artifactory/unittests-public/folder/file.foo.bar/1.0.0/file.foo.bar-1.0.0
https://audeering.jfrog.io/artifactory/unittests-public/folder/file.foo/1.0.0/file.foo-1.0.0.foo
https://audeering.jfrog.io/artifactory/unittests-public/folder/file/1.0.0/file-1.0.0.foo.bar
```

For consistency we have to enforce the same behavior for every backend implementation. So we should at least add a test for it.

**Comment by frankenjoe** [comment]
I might have a solution for the issue described here. As mentioned above, the following creates three different files on the backend:

```python
backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='')
backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='bar')
backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='foo.bar')
```

The reason this feels strange is that in all three cases `path` is the same.  But this is only because currently `path` has to end on `ext` as otherwise an error is raised. If we instead append `ext` when `path` does not end on `ext`, we could also write:

```python
backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='')
backend.put_file(local_file, '/folder/file.foo', '1.0.0', ext='bar')
backend.put_file(local_file, '/folder/file', '1.0.0', ext='foo.bar')
```

Now, it is much more obvious that we create three different files. And when listing the files under `/folder` we could then return:

```python
backend.ls('/folder)
[('/folder/file.foo.bar', '', '1.0.0'), ('/folder/file.foo', '.bar', '1.0.0'), ('/folder/file', '.foo.bar', '1.0.0')]
```

And again, it's more obvious that we get three different files.

It would also mean that the following three expressions are interchangeable:

```python
backend.put_file(local_file, '/folder/file.txt', '1.0.0')  # short
backend.put_file(local_file, '/folder/file, '1.0.0', ext='txt')
backend.put_file(local_file, '/folder/file.txt', '1.0.0', ext='txt')  # verbose
```

Of course, this is theoretically a breaking change. But only if code depends on the fact that an error is raised if `path` does not end on `ext`, which is not very likely.

**Comment by hagenw** [comment]
I still find it not obvious, e.g. will
```python
backend.put_file(local_file, '/folder/file.txt', '1.0.0', ext='txt')
```
create `/folder/file.txt` or `/folder/file.txt.txt`?

Couldn't we also solve this issue by removing `ext` altogether?

**Comment by frankenjoe** [comment]
I already thought hard whether there is a way we can get rid of `ext`, but I'm afraid it's too late.

E.g. let's assume we want to store a file as version `1.0.0` under the path `/folder/file.gz.tar` on Artifactory. Currently, if the user sets `ext=None` or `ext='tar'`, then we store it under `/host/repo/folder/file.gz/1.0.0/file.gz-1.0.0.tar`. But if the user sets `ext='gz.tar'` we store it under `/host/repo/folder/file/1.0.0/file.gz-1.0.0.gz.tar`. Now if we remove the `ext` argument, we do not know under which path we should look for the file. And in fact, if we remove the `ext` argument then the most obvious location would anway be  `/host/repo/folder/1.0.0/file.gz.tar`. But unfortunately for whatever reason already before we created `audbackend` we had already started to store files under the strange format `<basename>/<version>/<basename>-<version><ext>`. I guess now it's too late to change that.

**Comment by frankenjoe** [comment]
I guess it has to do with some Maven specification, at least they seem to use this format:

![image](https://user-images.githubusercontent.com/10383417/206663405-e5d64dc9-13ed-4b5f-9015-997b6b9ef98b.png)

**Comment by frankenjoe** [comment]
> I still find it not obvious, e.g. will
> 
> ```python
> backend.put_file(local_file, '/folder/file.txt', '1.0.0', ext='txt')
> ```
> 
> create `/folder/file.txt` or `/folder/file.txt.txt`?

We will document that it will create `/folder/file.txt`. Otherwise we are not backward compatible.

**Comment by hagenw** [comment]
As we have never directly used `audbackend` to store files on Artifactory couldn't we remove `ext` and make sure inside the Artifactory backend that files will be stored backward compatible? Because we know which `ext` we used inside `audb` and in other places.

**Comment by frankenjoe** [comment]
> As we have never directly used audbackend to store files on Artifactory

Are you sure? I think we use it in all our packages for a long time.

**Comment by hagenw** [comment]
What would happen with your proposal for:

```python
backend.put_file(local_file, '/folder/file.foo', '1.0.0', ext='foo.bar')
```

will it add another `foo` or use the already existing one?

**Comment by frankenjoe** [comment]
Since  `'/folder/file.foo'` does not end on `'foo.bar'` the result was `'/folder/file.foo.foo.bar'`.

**Comment by hagenw** [comment]
> As mentioned above, the following creates three different files on the backend:
>
> ```python
> backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='')
> backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='bar')
> backend.put_file(local_file, '/folder/file.foo.bar', '1.0.0', ext='foo.bar')
> ```

Another big hurdle here is that when adding a new backend that does not care what part is the file extension (and I expect most backends do not care), the developer has to spend extra effort to ensure that they really result in three different files.

**Comment by frankenjoe** [comment]
Yes, that is indeed very unfortunate. At least in #53 we know add tests for it. But we will also need to document this as it's indeed not obvious. So again - it's very unfortunate we have to deal with `ext`, but it's simply too late to get rid of it.

**Comment by frankenjoe** [comment]
So at least internally we should change the implementation to always pass `path='/folder/file' and `ext='.foo.bar` to the abstract functions instead of `path='/folder/file.foo.bar' and `ext='.foo.bar` as we currently do. Then the developer at least cannot ignore the extension :)

**Comment by frankenjoe** [comment]
I created https://github.com/audeering/audbackend/issues/58 to discuss a possible receipt how we can get rid of the `ext` argument as this seems the only real solution to this issue.
