### ISSUE TITLE
backend.versions() should raise error for empty folder/non existing file

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#61]
As discussed in https://github.com/audeering/audbackend/pull/53/files#r1048526273 we should update `audbackend.Backend.versions()` to raise an error for non-existing file sinstead to return an empty list to be in line with `audbackend.Backend.ls()`

**Comment by hagenw** [comment]
We should also think about usability here as there are use cases for which it makes sense to return an empty list, e.g. [in audb.publish() we do](https://github.com/audeering/audb/blob/f5c05a81bc7c92557e23dcd6cdc1a0ef3f9d72b1/audb/core/publish.py#L574-L581):

```python
versions = backend.versions(remote_header)
if version in versions:
    raise RuntimeError(
        'A version '
        f"'{version}' "
        'already exists for database '
        f"'{db.name}'."
    )
```

to check if the same version of a database was already published.
When you publish the very first version of that database, `versions` will be an empty list and it still works as expected.

Another use case is in [audb.versions()](https://github.com/audeering/audb/blob/f5c05a81bc7c92557e23dcd6cdc1a0ef3f9d72b1/audb/core/api.py#L589-L597), where we cycle through all repositories to collect available versions for a database. This also works easier if an empty list is returned:

```python
vs = []
for repository in config.REPOSITORIES:
    backend = audbackend.create(
        repository.backend,
        repository.host,
        repository.name,
    )
    header = backend.join(name, 'db.yaml')
    vs.extend(backend.versions(header))
```

**Comment by frankenjoe** [comment]
For me it would be fine to stick with the current behavior even if it then behaves differently as `audbackend.Backend.ls()`.

**Comment by frankenjoe** [comment]
Or: maybe we align both functions and let `audbackend.Backend.ls()` also return an empty list if a path does not exist. Originally we wanted to align the behavior with the `ls` function on `unix`, but there is a fundamental difference: on a regular file-system we have to distinguish between a non-existing folder and an empty folder, so we cannot return an empty list in both cases. But since we do not really support the concept of a folder (probably we should not even talk about folders, but rather sub-paths) with `Backend`, we don't have to make such a distinction. I.e. returning an empty list is equivalent to folder / path / sub-path does not exist and there is indeed not the need to raise an error.

**Comment by hagenw** [comment]
In https://github.com/audeering/audbackend/pull/87 we adjusted `versions()` that it now returns an empty list `[]` when the database cannot be found or that it raises a `BackendError` if their are problems with permission rights, or connection errors. As stated in https://github.com/audeering/audbackend/pull/87#issuecomment-1513199179 this has the disadvantage that the exact behavior now depends on the backend implementations. E.g. it might be that the Artifactory backend raises a custom permission error when a user has no access rights to a file, which would raise `BackendError`, or that it returns an `FileNotFoundError` which would lead to `[]`. The same question can be asked what happens if the authentication of the user does not work, or the username is not known. To provide a consistent implementation we would need to first specify what should be the expected results across backends and then a lot of tests (if possible) or manual trial and error in order to figure out the exact code we need in the backend implementation.

This problem would disappear if we say we just want one of the two options (`[]`, `BackendError`) to happen.
E.g. when we want to have always `[]` we can do in the general `Backend.version()` implementation:

```python
        utils.check_path_for_allowed_chars(path)

        try:
            vs = self._versions(path)
        except Exception
            vs = []

        return audeer.sort_versions(vs)
```
and in the `Artifactory._versions()` implementation we just need to do:

```python
        folder, _ = self.split(path)
        folder = self._folder(folder)
        folder = audfactory.path(folder)

        vs = [os.path.basename(str(f)) for f in folder if f.is_dir]
        # filter out versions of files with different extension
        vs = [v for v in vs if self._exists(path, v)] 

        return vs
```

**Comment by hagenw** [comment]
Of cause we loose information if we just return `[]` or `BackendError`, but we might even encounter backends that are not able to differentiate between those two cases. E.g. imagine a backend that raises the same `RuntimeError` if a file does not exist or the user password does not work. For the first case we would like to return `[]`, for the second case `BackendError`, but we have no way to differentiate between those two cases.

**Comment by frankenjoe** [comment]
> E.g. imagine a backend that raises the same RuntimeError if a file does not exist or the user password does not work.

In that case the backend has to catch the error and return False for `exists()` and an empty list for `ls()`. But I guess for most backends there should be a way to check if a file exists and for those backends it's useful that they can raise a `BackendError` in addition if something else goes wrong.

**Comment by hagenw** [comment]
> In that case the backend has to catch the error and return False for `exists()` and an empty list for `ls()`

But then it behaves different then a backend for which we would recognize the login error and which would raise a `BackendError` for the exact same behavior. So in one case the user would assume the file does indeed not exist (which might be wrong, because it was just a login error) and in the other case the user knows that it was a login error.

My proposed solution does of cause not solve all of this as it simply removes even more knowledge, so now a user doesn't know for any backend if the file exists or if it was a login error, but at least it would always return the same value, which makes it much easier to design applications.

---

If we stay with the current behavior we should at least provide a page in the documentation stating what the expected behavior is and add comments to the single backends.
For example at the moment we do the following in the Artifactory backend:

```python
        try:
            vs = [os.path.basename(str(f)) for f in folder if f.is_dir]
        except (FileNotFoundError, RuntimeError):
            vs = []
```
and I don't have a clue which cases we catch with the `RuntimeError` ;)

**Comment by frankenjoe** [comment]
> My proposed solution does of cause not solve all of this as it simply removes even more knowledge, so now a user doesn't know for any backend if the file exists or if it was a login error, but at least it would always return the same value, which makes it much easier to design applications.

I don't think removing knowledge is a good solution. And if a user doesn't care, she can simply use a try-catch for BackendError.

To me your last example actually sounds like an argument to not return an empty list if the file / folder does not exist, but also raise an BackendError in that case :)

**Comment by frankenjoe** [comment]
Since we are having a hard time to come to a conclusion if we should put usability over granularity I suggest we add an argument `suppress_backend_errors` to `exist()`, `ls()` and `versions()`. If set to `True` we catch possible backend errors and return `False` or an empty list.

**Comment by hagenw** [comment]
Sounds like a good idea.

I also created https://github.com/audeering/audbackend/issues/93 to track the missing documentation of catching certain errors.
