### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#67]
The corresponding pull request (https://github.com/audeering/audbackend/pull/66) is failing due to an error related with Artifactory and `Pathlib` which is most likely related to https://github.com/audeering/audfactory/issues/38

**Comment by hagenw** [comment]
Another related problem here is that we have hard-coded requirement for `dohq-artifactory ==0.7.742` which means we cannot include the fix we propose for `audfactory` in https://github.com/audeering/audfactory/pull/45.

@frankenjoe is there a possibility to make a bug fix release of `audbackend` or is this not possible before doing further changes? Or better: does the current `main` version work with `audb`?

**Comment by hagenw** [comment]
We introduced the

```
dohq-artifactory ==0.7.742
```
line in https://github.com/audeering/audbackend/pull/27, but I think it was an error/leftover as we fixed an issue there occuring with newer version of `dohq-artifactory`.
I also added `dohq-artifactory >=0.8.1` in https://github.com/audeering/audbackend/pull/66 and it works just fine, so I think we can simply fix this by removing the line and depending of a new version of `audfactory` after https://github.com/audeering/audfactory/pull/45 is included there.

**Comment by frankenjoe** [comment]
> depend on a new version of audfactory after https://github.com/audeering/audfactory/pull/45 is included there.

Now that we no longer use the maven-like file structure in `audbackend`, which is still used by `audfactory` we should probably get rid of the dependency to `audfactory` as proposed in #50

**Comment by hagenw** [comment]
If this is possible without much work, ok, but otherwise I would be in favor of a simple bug fix release to make `audb` work under Python 3.10

**Comment by frankenjoe** [comment]
The problem is that we cannot easily release a new version from the current master, as this changes the file structure we store files on Artifactory.

**Comment by hagenw** [comment]
OK, I was afraid of this already ;)

But I think there is still a way. We can go back in time of the commit history before you did the changes, apply the `audfactory` and `dohq-artifactory` version fix there and create a release at this position. We can then rewrite the history of the `main` branch afterwards.

**Comment by frankenjoe** [comment]
Or we wait until we have a new release of `audbackend`, there are still a few little changes missing.

**Comment by hagenw** [comment]
I would still prefer to first do a small bug fix release.
I created a branch `dev` from the current `main` branch. We could also select this as the default branch after we have done the bug fix release, so new pull requests will automatically compared against it. If then everything is ready we could merge it into `main` and make `main` the default branch again.

The question is how far do we need to go back in time for making the bug fix release:

```
92e0039 TST: remove pytest-flake from requirements (#69)  [Hagen Wierstorf] (HEAD -> dev, origin/main, origin/dev, origin/HEAD, main)
9bf8136 DOC: split up into sub-pages per class/function (#68)  [Hagen Wierstorf]
f6a157e TST: update Github Action versions (#65)  [Hagen Wierstorf]
098c862 TST: use main as default branch name (#64)  [Hagen Wierstorf]
46861fa TST: use pre-commit for flake8 checks (#63)  [Hagen Wierstorf]
2bd7d0f Reimplement Backend.ls() (#53)  [Johannes Wagner] (origin/master)
d7882d7 Add available() to list available backends (#56)  [Johannes Wagner]
3ce7c6d DOC: add docstring examples (#54)  [Johannes Wagner]
2b68ef4 do not convert . to / in url (#52)  [Johannes Wagner]
3385dea Remove Backend.path() and Backend._path() (#47)  [Johannes Wagner]
366cb20 Release v0.3.16 (#45)  [Johannes Wagner] (tag: v0.3.16)
```
Should we go directly to 366cb20 to be on the safe side?

**Comment by frankenjoe** [comment]
I guess so

**Comment by hagenw** [comment]
Done in https://github.com/audeering/audbackend/pull/66

As said I did now reqrite the history of `main` and set `dev` as the new default branch for further development. All pull requests are updated to have `dev` as target.
