### ISSUE TITLE
Adjust _non_existing_path_error to new dohq-artifactory version

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#72]
In `dohq-artifactory` 0.8.0 they did the following change:

* Raises ArtifactoryException instead of requests.HTTPError (https://github.com/devopshq/artifactory/issues/179)

We rely on `requests.HTTPError` at https://github.com/audeering/audbackend/blob/46a5acc63129eac2bc0757aceadcc698c4d4ef51/audbackend/core/artifactory.py#L213 in `audfactory.core.artifactory` and need to adjust it.

See also https://github.com/audeering/audfactory/issues/49

**Comment by frankenjoe** [comment]
With #87 we no longer catch specific errors on the backend, but raise any error as is wrapped by a generic `BackendError`.
