### ISSUE TITLE
Add author() and date() methods

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#75]
It is interesting to see who and when a file was uploaded or changed on the server.
At the moment we usually achieve this by using custom code for Artyifactory, e.g.

```python
url = f'{host}/{repository}/{name}/db/{version}/db-{version}.zip'
path = audfactory.path(url)
stat = path.stat()
published_by = stat.created_by
published_at = f'{stat.ctime:%Y-%m-%d}'
```

But it would be nice if we could abstract this code from the backend.

**Comment by hagenw** [comment]
Even if there are some backends that cannot provide those information `audbackend` could simply return an empty string.

**Comment by Bahaabrougui** [comment]
I can have a look at this if not yet started.

**Comment by hagenw** [comment]
No, it hasn't started yet.

Note, that at the moment we have a `main` branch for bug fix releases and a `dev` branch for bigger structural changes due to https://github.com/audeering/audbackend/issues/46.

As it would be nice to have the `author()` + `date()` feature not to far in the future, maybe it makes sense to create a pull request against `main`.

/cc @frankenjoe

**Comment by frankenjoe** [comment]
I would prefer we first finish #46, adding those methods will be straight-forward afterwards.

**Comment by frankenjoe** [comment]
Ok, so let's try to figure out how this could be implemented. Some thoughts:

1. Should we add a `date` and `author` argument with default parameters to the `put_*()` functions? Or would you not allow the user to set it and always derive it automatically it and only pass it on to `_put_*()`?
2. We add  `Backend.date()` / `Backend.author()` that call corresponding `_date()` and `_author()` methods on the implementation. These functions are supposed to return the value that was provided with `_put_*()`. If this is not possible they return an empty string or maybe `None`?

**Comment by hagenw** [comment]
I would always derive it automatically. If a backend is not able to provide that information I would return `None`.

BTW, you stated that first #46 should be finished, is this still true?

**Comment by frankenjoe** [comment]
> I would always derive it automatically. If a backend is not able to provide that information I would return None.

Ok, so we do not add a `date` and `author` argument to `_put()` but simply assume that they take care of storing a date and an author?

> BTW, you stated that first https://github.com/audeering/audbackend/issues/46 should be finished, is this still true?

Already working on closing #46.

**Comment by hagenw** [comment]
> > I would always derive it automatically. If a backend is not able to provide that information I would return None.
> 
> Ok, so we do not add a `date` and `author` argument to `_put()` but simply assume that they take care of storing a date and an author?

If the information is not available on the backend it could be handled as with  https://github.com/audeering/audbackend/issues/113. The date could easily be calculated and stored when putting the file, and looking at https://stackoverflow.com/a/842096 it should also be possible for the user.

**Comment by frankenjoe** [comment]
> The date could easily be calculated and stored when putting the file

Sure, but the question is if the backend implementation is responsible for it or if we do it in `Backend` and pass it to the `_put()` function.

**Comment by hagenw** [comment]
Ah, ok, now I get it. The `Backend` should be responsible for it, otherwise `author` will not match the usernames on some backends (e.g. Artifactory).

**Comment by frankenjoe** [comment]
And this would be an argument to simply let the implementation take care of it.

**Comment by frankenjoe** [comment]
But maybe we simply start an implementation and see how it goes :)
