### ISSUE TITLE
Consider adding file extension to `Backend.put_archive()`

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#78]
At the moment our call to `audbackend.Backend.put_archive()` is:

```python
backend.put_archive(tmp, files, 'folder/name', '2.0.0')
```

which is slightly different from all the other functions that require a user to provide the file extension as well with the name.
In this case it would be:

```python
backend.put_archive(tmp, files, 'folder/name.zip', '2.0.0')
```

One of the reasons we didn't included it here was that the function can only create a ZIP archive at the moment,
which means if we add support for `folder/name.zip` we have to raise an error if another file extension is provided instead.

**Comment by frankenjoe** [comment]
If we want to support other archive formats, I would rather introduce a new argument that can be set to the desired algorithm and defaults to `zip`.

**Comment by hagenw** [comment]
It's not about supporting other archive formats. I just found it very unintuitive that I'm not allowed to write `put_archive(tmp, files, 'folder/name.zip', '2.0.0')` as we now provide file extensions in all other methods.

**Comment by hagenw** [comment]
BTW, the same argumentation affects `Backend.get_archive()`.

---

> But why should the user bother with the extension on the backend then?

With most programs that create a ZIP file you can also select the name of it. E.g. when providing `folder/archive`, I would expect it to be stored under `folder/archive` and not `folder/archive.zip`.

**Comment by frankenjoe** [comment]
> With most programs that create a ZIP file you can also select the name of it. E.g. when providing folder/archive, I would expect it to be stored under folder/archive and not folder/archive.zip.

Without the extension `.zip` would preview on Artifactory still work? E.g.:

![image](https://user-images.githubusercontent.com/10383417/231678404-5c8b5d8b-7d34-49d1-8a96-17301f78a005.png)

Features on other backends we add in the future may also benefit from the extension.

**Comment by frankenjoe** [comment]
I have now created https://github.com/audeering/audbackend/pull/82, but it still forces `.zip`. If we really want to allow arbitrary file names we have two options:

1. remove the .zip from all archives when we rename the files on our backends (but we should check if preview on Artifactory is still supported in that case)
2. update our packages to explicitly add `.zip` to the archive names

**Comment by hagenw** [comment]
I would not be in favor of not storing archives with `*.zip` as extension name. I just wanted to provide the opportunity that a user specifies the file extension for archives. 
But maybe I will be ok with #82 for a start.

**Comment by frankenjoe** [comment]
In #82 we now decided that the user has to set the archive extension.
