### ISSUE TITLE
Should Backend.latest_version() raise FileNotFoundError?

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#84]
Most of the backend methods raise `FileNotFoundError` when a `path` argument is provided that does not exist on the server.
`Backend.latest_version()` raises `RuntimeError` instead. One difference is that `latest_version()` does not get `version` and does hence not look for a single file.

**Comment by frankenjoe** [comment]
Ah good you raise that issue. I think `FileNotFoundError` makes more sense. And I have a related question: should maybe `Backend.versions()` should raise `FileNotFoundError` in the first place? At the moment it returns an empty list I think.

**Comment by hagenw** [comment]
It might be easier to work with `[]` instead of having to catch different errors, because `Backend.versions()` might not only raise `FileNotFoundError` but also some permissions errors which can be anything across different backends at the moment. If we make sure that a backend would always raise the same error for no permissions, we could think about changing it, but until then we cannot expect that the users can know which error she has to catch.

**Comment by frankenjoe** [comment]
Ok, but somehow we have the problem with `get_file()` and here we raise a `FileNotFoundError` even if the file exists but the user has not the right permission. So maybe we should keep it simple and always raise `FileNotFoundError` and not care about permission or other problems?

**Comment by hagenw** [comment]
No, at the moment we always return `[]`, which I think is fine.
If we want to raise errors instead we need to make sure that all backends will raise the same error types for the same behavior, which I think is not possible. E.g. if a file does not exists on a backend for which you cannot login, you will not get a `FileNotFoundError`, whereas for a backend that does not require login you will get a `FileNotFoundError`.

**Comment by hagenw** [comment]
> We can catch any error and then raise FileNotFoundError

Yes, that what I stated above. If we include those changes then we can update the behavior of `versions()`, but not before.

**Comment by frankenjoe** [comment]
Regarding 2. - I just came across https://github.com/audeering/audbackend/issues/61 and there you propose to raise an error instead of returning an empty list.

**Comment by frankenjoe** [comment]
As all other functions `Backend.latest_version()` will now raise `BackendError`, see #87
