### ISSUE TITLE
Should ls('/') raise an error if repository does not exist?

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#86]
We decided that `ls('/')` should return an empty list if there are no files in the repository yet. But currently we also return an empty list if the repository does not even exist.

```python
backend = audbackend.create(
    'file-system',
    'host',
    'does-not-exist',
)
backend.ls('/')
```
```
[]
```

I wonder if we should raise an error in that case?

**Comment by hagenw** [comment]
The question is who should be responsible for creating the repo in the first place.
E.g. you might argue that `audbackend.create()` should raise the error already if the repo does not exist.
On the other hand for the file-system backend it might also be handy if the repo is generated on the fly when the first file is added, which seems to happen anyway at the moment:

```python
backend = audbackend.create(
    'file-system',
    'host',
    'does-not-exist',
)
path = audeer.touch('file.txt')
backend.put_file(path, 'file.txt', '1.0.0')
backend.ls()
```
returns
```
[('file.txt', '1.0.0')]
```

To be in line with that behavior, maybe even `backend.ls()` should then create the repo and return an empty list?

The behavior should be identical for all backends, I guess we need to raise the error already for `audbackend.create()` if the repo does not exists or the user has no access rights to it.

**Comment by frankenjoe** [comment]
> The behavior should be identical for all backends, I guess we need to raise the error already for `audbackend.create()` if the repo does not exists or the user has no access rights to it.

Yes the behavior should be identical for all backends and I think the repository should exist and not be created on the fly since this might not be always possible. So  `audbackend.create()` would indeed be the best place to raise an error if the repository does not exist. I see two options here:

1. Add a method that checks if the repository exists and that  every backend has to implement
2. Create and delete a temporary file in the repository

**Comment by frankenjoe** [comment]
> On the other hand for the file-system backend it might also be handy if the repo is generated on the fly

A backend could still create the repository on the fly in the constructor.

**Comment by frankenjoe** [comment]
We now create the repository with `audbackend.create()` and if this fails raise an error, see #91
