### ISSUE TITLE
put_archive(): make `files` an optional argument

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#88]
With `put_archive()` we currently force the user to select the files that should be included in an archive. But maybe we should make `files` an optional argument and by default include all files under `src_root` instead?

**Comment by hagenw** [comment]
So basically changing
```python
Backend.put_archive(src_root, files, dst_path, version, *, tmp_root=None, verbose=False)
```
to
```python
Backend.put_archive(src_root, dst_path, version, *, files=None, tmp_root=None, verbose=False)
```
and
```
    files: if not ``None`` only the files provided here
        with their relative path from ``src_root``
        are included
```

I like the idea, as ``put_archive()`` becomes then symmetrical to ``get_archive()`` as we have with ``put_file()`` and ``get_file()``.

BTW, how to we handle relative paths that are located outside the folder at the moment?
E.g.
```python
Backend.put_archive('folder', '../a.txt', ...)
```

**Comment by frankenjoe** [comment]
I wonder if make sense we first add support for `files=None` in `audeer.create_archive()`?

**Comment by hagenw** [comment]
Why not, but then you should be fast: https://github.com/audeering/audeer/pull/100 :)

**Comment by frankenjoe** [comment]
> BTW, how to we handle relative paths that are located outside the folder at the moment?

I checked and there are no checks currently in `create_achive()`, see https://github.com/audeering/audeer/issues/101

**Comment by frankenjoe** [comment]
I also created https://github.com/audeering/audeer/issues/102 which suggests supporting `files=None`.
