### ISSUE TITLE
Artifactory: store authentication

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#90]
Relates to #50 

In the Artifactory backend we currently rely on the `path` function from `audfactory`. Every time it is called it tries to read username and API key. If we assume that those will not change during a session, we can maybe retrieve them once when the backend object is created and reuse them afterwards.

**Comment by hagenw** [comment]
Good idea, this might also allow us to tackle https://github.com/audeering/audbackend/issues/50, as the authentication is the biggest feature of `audfactory` we are using at the moment.

**Comment by frankenjoe** [comment]
Done in #50
