### ISSUE TITLE
Document which errors we are excepting in Artifactory._versions()

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#93]
As stated in https://github.com/audeering/audbackend/issues/61#issuecomment-1514265365 we should document when we except certain backend errors to return an empty list instead of raising a `BackendError`.

In `audbackend.Artifactory._versions()` we have https://github.com/audeering/audbackend/blob/cf2f45034420427b75b9f4ad7939d0e8b3b4c42e/audbackend/core/artifactory.py#L170-L173

As it is not obvious which cases are considered by `RuntimeError` we should document them (or maybe remove them).

**Comment by frankenjoe** [comment]
Does this still apply? With #94 we now raise all original errors or none.

**Comment by hagenw** [comment]
No, this is no longer needed as we now implemented the simple solution to just pass on all errors.
