### ISSUE TITLE
Consider renaming audbackend.create()

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#99]
As discussed in https://github.com/audeering/audbackend/pull/98#discussion_r1172625244 where we are adding `audbackend.delete()`, `audbackend.create()` is slightly misleading as in most cases it does not create a new repository on the provided backend, but just returns a `Backend` instance that has access to that repo. If the repo does not exists it is also created, but this is just a minor use-case.

A better fit would be to call it `audbackend.open()` or `audbackend.init()`.

**Comment by frankenjoe** [comment]
>  returns a Backend instance that has access to that repo

So maybe `Backend.access()` :)

**Comment by hagenw** [comment]
I would also not use `Backend.init()` as it feels similar to `Backend.create()`, e.g. it initializes a repository.

**Comment by frankenjoe** [comment]
One advantage of such a design would be that as long as a user uses `access()` she cannot accidentally create a new repository, as most of the time we want to work on an already existing repository.

**Comment by hagenw** [comment]
Makes sense, the only downside us that `audbackend.create()` might not be available for all backends. But I guess it is ok, if we document backends that don't work in its docstring and document in the code what a developer of a new backend should do if repositories cannot be created via the API.

**Comment by frankenjoe** [comment]
In `audb`, `audbenchmark` and `audmodel` we call the functions `publish()` and `load()`. Maybe we simply stick to this naming scheme here, too?

**Comment by hagenw** [comment]
Not sure about that, `publish()` and `load()` really shuffle data around. This would be an argument to rename `put_file()` to `publish_file()` and `get_file()` to `load_file()`, but I don't see a need for it.

I think the names `access()` and `create()` are good choices.
